name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: anupama.deo@gramener.com
      run: |
        python -c "
        import json
        with open('email.json') as f:
            file = json.load(f)
        print(file['email'])
        "
