name: Git-Action

on : push

jobs:
  git-action:
    runs-on: ubuntu-latest
    steps:
      - name: anupama.deo@gramener.com
        run: | #python
          import json
          with open('email.json') as f:
            file = json.loads(f)
          print(file['email'])
        
    
